### ISSUE TITLE
Fix footnote content when present in a hx or a strong tag

### ISSUE THREAD

**Issue by brunob** [lemonmade/bigfoot#40]
Hi @lemonmade i think it should be useful to add this rules in styles :

```css
.bigfoot-footnote__container { font-size: initial; font-weight: initial; line-height: initial; }
```
This should avoid to get a blod text when a footnote is in a strong tag, or a h2 like content when the footnote is in a h2 tag.

Any thought about it ?
